pipeline {
  agent {
    node {
      label 'maven'
    }
  }

  parameters {
    string(name: 'PROJECT_VERSION',defaultValue: 'v0.0Beta',description: '')
    string(name: 'PROJECT_NAME',defaultValue: '',description: '')
  }

  environment {
          DOCKER_CREDENTIAL_ID = 'dockerhub-id'
          GITEE_CREDENTIAL_ID = 'gitee-id'
          KUBECONFIG_CREDENTIAL_ID = 'demo-kubeconfig'
          REGISTRY = 'docker.io'
          DOCKERHUB_NAMESPACE = 'crown233'
          GITEE_ACCOUNT = 'zhaocan1872751113'
          SONAR_CREDENTIAL_ID = 'sonar-qube'
  }

  stages {
    stage('拉取代码') {
      steps {
        git(credentialsId: 'gitee', url: 'https://gitee.com/zhaocan1872751113/gulimall.git', branch: 'main', changelog: true, poll: false)
        sh 'echo 正在构建 $PROJECT_NAME  版本号：$PROJECT_VERSION'
      }
    }
  }
}